import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useUser } from "../../context/UserContext";
import api from "../../services/api";
import { Toast , ToastContainer } from "react-bootstrap";
import "react-toastify/dist/ReactToastify.css";
import { toast } from "react-toastify";

interface Row {
  id: number;
  salesMan: string;
  smId: string;
  amount: number | string;
  debitAccount: string;
  creditAccount: string;
  notes?: string;
  errors?: { salesMan?: string; amount?: string };
}
interface ClaimVoucherProps {
  onSaveSuccess?: () => void;
}


const sampleAccounts = [
  "Travelling Expense",
  "Travelling Expense - FOREIGN",
  "Travelling Expense - PC"
];
const cerditDropdown =[
  "Income Tax Refund",
  "Insurance",
  "12% GST Local purchase",
  "12% GST LOCAL SALES A/C",
]

const sampleNotes = ["--", "Travel expenses", "Office supplies", "Client meeting", "Misc"];

const ClaimVoucher: React.FC<ClaimVoucherProps> = ({ onSaveSuccess }) => {
  const { role, user } = useUser();
  const navigate = useNavigate();
  const roleName = role?.roleName || "";
  const isFinance = roleName === "Finance" || roleName === "Finance Department" || roleName === "Accountant";

  // Doc Id is generated by the backend; keep blank until server returns it
  const [docId, setDocId] = useState<string>("");
  const [docDate, setDocDate] = useState<string>(new Date().toISOString().slice(0, 10));
  const [fromDate, setFromDate] = useState<string>(new Date().toISOString().slice(0, 10));
  const [toDate, setToDate] = useState<string>(new Date().toISOString().slice(0, 10));
  const [status, setStatus] = useState<string>("pending");
  const [rows, setRows] = useState<Row[]>([
    { id: 1, salesMan: "", smId: "", amount: "", debitAccount: "", creditAccount: "", notes: "" },
  ]);
  const [saving, setSaving] = useState(false);
  const [salesUsers, setSalesUsers] = useState<{ userId: number; username: string }[]>([]);

  // Fetch users assigned to Sales Representative role
  React.useEffect(() => {
    const fetchSalesUsers = async () => {
      try {
        const resp = await fetch('${process.env.REACT_APP_API_BASE_URL}/UmUserRole/user-roles');
        const json = await resp.json();
        if (json && Array.isArray(json.data)) {
          const sales = json.data
            .filter((u: any) => (u.roleName || '').toLowerCase() === 'sales representative')
            .map((u: any) => ({ userId: u.userId, username: u.username }));
          // dedupe by userId
          const map: Record<number, { userId: number; username: string }> = {};
          sales.forEach((s: any) => { map[s.userId] = s; });
          setSalesUsers(Object.values(map));
        }
      } catch (e) {
        // ignore
      }
    };
    fetchSalesUsers();
  }, []);

  if (!isFinance) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="bg-white p-8 rounded shadow text-center">
          <div className="text-xl font-semibold">Access denied</div>
          <div className="text-sm text-gray-500 mt-2">This page is only accessible to Finance users.</div>
        </div>
      </div>
    );
  }

  const addRow = () => {
    setRows((r) => [...r, { id: Date.now(), salesMan: "", smId: "", amount: "", debitAccount: "", creditAccount: "", notes: "" }]);
  };

  const removeRow = (id: number) => {
    setRows((r) => r.filter((x) => x.id !== id));
  };

  const updateRow = (id: number, patch: Partial<Row>) => {
    setRows((r) => r.map((x) => (x.id === id ? { ...x, ...patch } : x)));
  };

  const totalAmount = rows.reduce((s, r) => s + (Number(r.amount) || 0), 0);

const handleSave = async () => {
  let hasError = false;

  const updatedRows = rows.map((r) => {
    const errors: { salesMan?: string; amount?: string } = {};
    if (!r.salesMan || r.salesMan.trim() === "") {
      errors.salesMan = "Sales Man is required";
      hasError = true;
    }
    // if (!r.amount || Number(r.amount) <= 0) {
    //   errors.amount = "Amount is required";
    //   hasError = true;
    // }
    return { ...r, errors };
  });

  setRows(updatedRows);

  if (hasError) return; // prevent saving if there are errors

  // Payload and API call (same as before)
  const payload = {
    date: docDate,
    fromDate,
    toDate,
    status,
    totalAmount,
    userCreated: user?.userId ?? 1,
    userUpdated: user?.userId ?? 1,
    items: updatedRows.map((r) => ({
      salesMan: r.salesMan,
      smId: r.smId,
      debitAccount: r.debitAccount,
      creditAccount: r.creditAccount,
      amount: Number(r.amount),
      notes: r.notes || "",
    })),
  };

  setSaving(true);
  try {
    const resp = await api.post("ClaimVouchers", payload);
    const returned = resp?.data ? (resp.data.data ?? resp.data) : null;
    if (returned && (returned.docId || returned.docId === 0)) setDocId(String(returned.docId));
   toast.success("Claim voucher saved successfully.");
    navigate("/claims/vouchers");
     onSaveSuccess?.();
    handleNew();
  } catch (err) {
    console.error(err);
    toast.error("Failed to save claim voucher. Please try again.")
  } finally {
    setSaving(false);
  }
};



  const handleNew = () => {
    setDocId("");
    setDocDate(new Date().toISOString().slice(0, 10));
    setFromDate(new Date().toISOString().slice(0, 10));
    setToDate(new Date().toISOString().slice(0, 10));
    setStatus("pending");
    setRows([{ id: Date.now() + 1, salesMan: "", smId: "", amount: "", debitAccount: "", creditAccount: "", notes: "" }]);
  };

  return (
    <div className="min-h-[60vh] bg-gray-50 py-6 px-4">
      <div className="max-w-6xl mx-auto bg-white rounded-lg shadow p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h1 className="text-xl font-semibold">Executive Claim Voucher</h1>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={handleNew} className="px-3 py-2 bg-gray-100 rounded">New</button>
            <button onClick={handleSave} disabled={saving} className={`px-3 py-2 rounded ${saving ? 'bg-gray-400 text-white' : 'bg-green-600 text-white'}`}>
              {saving ? 'Saving...' : 'Save'}
            </button>
            <button onClick={() => window.print()} className="px-3 py-2 bg-blue-600 text-white rounded">Print</button>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-4 mb-4">
          <div>
            <label className="text-sm text-gray-600">Doc Id</label>
            <input value={docId} placeholder="Auto-generated by server" readOnly disabled className="w-full mt-1 p-2 border rounded bg-gray-100 text-gray-700" />
            <div className="text-xs text-gray-500 mt-1 italic">Doc Id is auto-generated by the server on save.</div>
          </div>
          <div>
            <label className="text-sm text-gray-600">Doc Date</label>
            <input type="date" value={docDate} onChange={(e) => setDocDate(e.target.value)} className="w-full mt-1 p-2 border rounded" />
          </div>
          <div>
            <label className="text-sm text-gray-600">Status</label>
            <select value={status} onChange={(e) => setStatus(e.target.value)} className="w-full mt-1 p-2 border rounded">
              <option value="generate Voucher">Generate Voucher</option>
              <option value="pending">Pending</option>
            </select>
          </div>
          <div>
            <label className="text-sm text-gray-600">From Date</label>
            <input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} className="w-full mt-1 p-2 border rounded" />
          </div>
          <div>
            <label className="text-sm text-gray-600">To Date</label>
            <input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} className="w-full mt-1 p-2 border rounded" />
          </div>
        </div>

        <div className="overflow-x-auto border rounded">
          <table className="min-w-full">
            <thead className="bg-gray-100">
              <tr>
                <th className="px-3 py-2 border">S No</th>
                <th className="px-3 py-2 border">Sales Man <span className="text-red-500">*</span></th>
                <th className="px-3 py-2 border">SM ID</th>
                 <th className="px-3 py-2 border">Amount</th>
                <th className="px-3 py-2 border">Debit Account</th>
                <th className="px-3 py-2 border">Credit Account</th>
                <th className="px-3 py-2 border">Notes</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r, idx) => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="px-3 py-2 border">{idx + 1}</td>
                        <td className="px-3 py-2 border">
                   <div className="flex flex-col">


                   {salesUsers.length > 0 ? (
                   <select
                   value={r.smId}
                 onChange={(e) => {
                   const id = e.target.value;
                   const su = salesUsers.find((s) => String(s.userId) === id);
                   updateRow(r.id, { smId: id, salesMan: su ? su.username : "" });
                   }}
                    className={`w-full md:w-[200px] p-2 mt-1 text-sm border rounded ${
                     r.errors?.salesMan ? "border-red-500" : "border-gray-300"
                   }`}
                >
                  <option value="">-- Select --</option>
                   {salesUsers.map((s) => (
                  <option key={s.userId} value={String(s.userId)}>
                  {s.username}
                </option>
                ))}
          </select>
                 ) : (
      <input
        value={r.salesMan}
        onChange={(e) => updateRow(r.id, { salesMan: e.target.value })}
        placeholder="Sales Man"
        className={`w-full md:w-[200px] p-2 mt-1 text-sm border rounded ${
          r.errors?.salesMan ? "border-red-500" : "border-gray-300"
        }`}
      />
     )}

    {/* Inline error */}
    {r.errors?.salesMan && <span className="text-red-500 text-xs mt-1">{r.errors.salesMan}</span>}
  </div>
</td>


                  <td className="px-3 py-2 border">
                      <input
                      value={r.smId}
                      onChange={(e) => updateRow(r.id, { smId: e.target.value })}
                      className="w-full p-1"
                      />
                         </td>
                           <td className="px-3 py-2 border">
  <div className="flex flex-col">
    <input
      type="number"
      value={String(r.amount)}
      onChange={(e) => updateRow(r.id, { amount: e.target.value })}
      placeholder="Amount"
      className={`w-full p-2 border rounded ${
        r.errors?.amount ? "border-red-500" : "border-gray-300"
      }`}
    />
    {/* Inline error */}
    {r.errors?.amount && <span className="text-red-500 text-xs mt-1">{r.errors.amount}</span>}
  </div>
</td>
                  <td className="px-3 py-2 border">
                    <select value={r.debitAccount} onChange={(e) => updateRow(r.id, { debitAccount: e.target.value })} className="w-full p-1">
                      <option value="">--</option>
                      {sampleAccounts.map((a) => (<option key={a} value={a}>{a}</option>))}
                    </select>
                  </td>
                  <td className="px-3 py-2 border">
                    <select value={r.creditAccount} onChange={(e) => updateRow(r.id, { creditAccount: e.target.value })} className="w-full p-1">
                      <option value="">--</option>
                      {cerditDropdown.map((a) => (<option key={a} value={a}>{a}</option>))}
                    </select>
                  </td>
                  <td className="px-3 py-2 border">
                    <div className="flex gap-2 items-center">
                      <select value={r.notes} onChange={(e) => updateRow(r.id, { notes: e.target.value })} className="p-1 flex-1">
                        {sampleNotes.map((n) => (<option key={n} value={n === "--" ? "" : n}>{n}</option>))}
                      </select>
                      <button onClick={() => removeRow(r.id)} className="px-2 py-1 bg-red-500 text-white rounded">Remove</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-4 flex items-center justify-between">
          <div>
            <button onClick={addRow} className="px-3 py-2 bg-gray-200 rounded">Add Row</button>
          </div>
          <div className="text-right">
            <div className="text-sm text-gray-500">Total Amount</div>
            <div className="text-lg font-bold">₹{totalAmount.toFixed(2)}</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ClaimVoucher;
